var count =0;

var thefunc = $(document).ready(function(){
$("#btn").click(function(){
    let calcName= "calculator"+count;
    count+=1;

    $("div").append("<form name=\""+calcName+"\"><table><tr> <td colspan=\"4\"><input type=\"text\" name=\"display\" id=\"display\" disabled></td>   </tr>   <tr>      <td><input type=\"button\" name=\"one\" value=\"1\" onclick=\""+calcName+".display.value += '1'\"></td>      <td><input type=\"button\" name=\"two\" value=\"2\" onclick=\""+calcName+".display.value += '2'\"></td>      <td><input type=\"button\" name=\"three\" value=\"3\" onclick=\""+calcName+".display.value += '3'\"></td>      <td><input type=\"button\" class=\"operator\" name=\"plus\" value=\"+\" onclick=\""+calcName+".display.value += '+'\"></td>   </tr>   <tr>      <td><input type=\"button\" name=\"four\" value=\"4\" onclick=\""+calcName+".display.value += '4'\"></td>      <td><input type=\"button\" name=\"five\" value=\"5\" onclick=\""+calcName+".display.value += '5'\"></td>      <td><input type=\"button\" name=\"six\" value=\"6\" onclick=\""+calcName+".display.value += '6'\"></td>      <td><input type=\"button\" class=\"operator\" name=\"minus\" value=\"-\" onclick=\""+calcName+".display.value += '-'\"></td>   </tr>   <tr>      <td><input type=\"button\" name=\"seven\" value=\"7\" onclick=\""+calcName+".display.value += '7'\"></td>      <td><input type=\"button\" name=\"eight\" value=\"8\" onclick=\""+calcName+".display.value += '8'\"></td>      <td><input type=\"button\" name=\"nine\" value=\"9\" onclick=\""+calcName+".display.value += '9'\"></td>      <td><input type=\"button\" class=\"operator\" name=\"times\" value=\"x\" onclick=\""+calcName+".display.value += '*'\"></td>   </tr>   <tr>      <td><input type=\"button\" id=\"clear\" name=\"clear\" value=\"c\" onclick=\""+calcName+".display.value = ''\"></td>      <td><input type=\"button\" name=\"zero\" value=\"0\" onclick=\""+calcName+".display.value += '0'\"></td>      <td><input type=\"button\" name=\"doit\" value=\"=\" onclick=\""+calcName+".display.value = eval("+calcName+".display.value)\"></td>      <td><input type=\"button\" class=\"operator\" name=\"div\" value=\"/\" onclick=\""+calcName+".display.value += '/'\"></td>   </tr></table></form>");
  });
});